### PR TITLE
Bit of proposed re-organization to let things grow out conceptually

### PR DESCRIPTION
**Pull request by rovangju**
Since this could be quickly going down a few paths involving a bit more complexity (e.g.: stdin efficiency, abstractions on adding/managing templates via YAML or something); I thought maybe re-organizing the package a bit into more distinct components might be useful?

### CODE REVIEW

**Comment by oliverisaac** [comment]
Is there a reason to nest it under `/pkg/templating` vs just `/templating`? 

My next steps (after fixing bugs I thought of last night) was going be adding a directory for the exe code so I can test the input into the exe. That wouldn't belong in the `pkg` directory I don't think?

**Comment by rovangju** [comment]
Idea behind the `pkg/` convention is to keep the root file space intuitive. Anything in `pkg` is going to be go code (a common convention). Supposin you wanted to add a directory called 'config' or 'templates' that was not really go centric - you gotta ferret them away somewhere, and IMHO putting them in with go code is kinda ... ugly. 

As a codebase grows it gets a bit more difficult to grok structurally:

`tgrep/parser`
may someday turn into:

```
tgrep/config/parser
tgrep/template/parser 
```

or (this wouldn't be smart given config and template parsing would be different beasts):

```
tgrep/parser/config
tgrep/parser/template
```

The other thing I noticed is that tgrep -is- your module already.
Thus the code shows up like this now:

```
import (
	...
	"github.com/oliverisaac/tgrep/tgrep"
)
```

If you consider how that may look as things grow:

Keep everything under tgrep directory in code root:
```
import (
	...
	"github.com/oliverisaac/tgrep/tgrep/template/parser",
        "github.com/oliverisaac/tgrep/tgrep/config/parser"
)
```

or, directories under the code root - which looks good with the exception of polluting the directory as described above:

```
import (
	...
	"github.com/oliverisaac/tgrep/template/parser",
        "github.com/oliverisaac/tgrep/config/parser"
)
```

with the `pkg` path, it turns into this, which is really close to above, just trades off the addition of the extra directory to keep your root directory more flexible: 

```
import (
	...
	"github.com/oliverisaac/tgrep/pkg/template/parser",
        "github.com/oliverisaac/tgrep/pkg/config/parser"
)
```

There is another option of flipping it on it's head, whereby the convention is that all directories can/should contain go code under the code base root directory, but then you'll likely need to hunt out an exception process for things that are assets of sorts, e.g.: yaml/config files, etc. 

Ok... maybe I just have OCD...

**Comment by rovangju** [comment]
For the `exe` part I'm assuming you're talking about the stdin reading? It could very much so be a part of a parsing or streams or io "package".

**Comment by rovangju** [comment]
Something that go into my head was a YAML format to define the regex templates, e.g.:

```
templates:
- name: ipv4
  template: ([1334].regex)
  tests:
  - it: "Should match 4 octets"
    passingInputs:
      - "0.0.0.0"
      - "0.0.0.1"
    failingInputs:
      - "256.0.0.1"
      - "1.0.0.0.1"
      - "shit"
      - "one.two.three.four"
```

We could slurp it into a type and use it to generate help output, e.g.: "available built-in templates", and drive the tests. 
Then, we could eventually introduce a flag to allow someone to extend with their own templates in this format.

**Comment by rovangju** [comment]
Oh! One last thing , you could also do 'internal': 
https://github.com/golang-standards/project-layout

**Comment by oliverisaac** [comment]
Okay, cool, that all makes sense. If you merge in origin/main this should be mergable :)

**Comment by oliverisaac** [comment]
I love the idea of a yaml file to define the templates and generating the code/tests for that. Would be a super clean way to handle all of it :)

**Pull request merged**
